### ISSUE TITLE
Standardize installation instructions

### ISSUE THREAD

**Issue by LucioFranco** [timberio/docs#13]
`/{type}/{name}/installation`

**Comment by binarylogic** [comment]
I'm moving this back to "To-do". We need to:

- [ ] Revive the Ruby manual instructions
- [ ] Update the pages / nav to match that of Elixir
- [ ] Ensure that _every_ installation page has a numbered list (`<ol>`). The frontend requires this structure consistency to display instructions properly in the app.
- [ ] Determine what to do with the HTTP / STDOUT installation pages.
- [ ] Add `popular` front-matter tags to platforms that are popular.
- [ ] Add `aws` tag
- [ ] Add `container` tag
- [ ] Talk to Ben about other tags
