### ISSUE TITLE
Duplicated section: "Log Formats & Parsing"

### ISSUE THREAD

**Issue by jsonmaur** [timberio/docs#2]
@zsherman Any reason why the "Log Formats & Parsing" section is duplicated between the `timber-concepts` and `timber-service` sidebar groups? They seem to have the same content.

https://timber.io/docs/concepts/log-formats-and-parsing
https://timber.io/docs/service/log-formats-and-parsing

**Comment by zsherman** [comment]
@binarylogic was the one who added those, not sure

**Comment by binarylogic** [comment]
That's a mistake, it should be under "service" only.
